export { default as sortReducer } from './sortSlice'
export { default as categoryReducer } from './categorySlice'
export { default as pizzaReducer } from './pizzaSlice'
export { default as searchReducer } from './searchSlice'
export { default as cartReducer } from './cartSlice'
