export { default as sortReducer } from './sort/slice'
export { default as categoryReducer } from './category/slice'
export { default as pizzaReducer } from './pizza/slice'
export { default as searchReducer } from './search/slice'
export { default as cartReducer } from './cart/slice'
